USE [master]
GO

/****** Object:  Database [DiagnosticAppDB]    Script Date: 4/22/2017 6:26:49 PM ******/
CREATE DATABASE [DiagnosticAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DiagnosticAppDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DiagnosticAppDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DiagnosticAppDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\DiagnosticAppDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DiagnosticAppDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DiagnosticAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DiagnosticAppDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DiagnosticAppDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DiagnosticAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DiagnosticAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DiagnosticAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DiagnosticAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DiagnosticAppDB] SET  MULTI_USER 
GO

ALTER DATABASE [DiagnosticAppDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DiagnosticAppDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DiagnosticAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DiagnosticAppDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DiagnosticAppDB] SET  READ_WRITE 
GO


